### ISSUE TITLE
Linking additional containers

### ISSUE THREAD

**Issue by dfetterman** [clue/docker-frontroute#15]
This is more or less related to docker functionality but how would you go about linking to additional containers once you have frontroute running?

I imagine if docker allows you to add additional linked containers to an already running container, apply-from-env.php would need to run again in order to recreate /etc/nginx/sites-enabled/default and nginx would need to restart for these settings to be applied..

**Comment by dfetterman** [comment]
Nevermind, I've got a script that stops the running proxy container, removes the stopped proxy container, pulls a list of containers from a csv file and runs the docker run command linking the proxy to the containers. If anyone is interested in this, please let me know.

Dane

**Comment by clue** [comment]
Thanks for your interesting input! :+1: 

> This is more or less related to docker functionality but how would you go about linking to additional containers once you have frontroute running?

I'm not aware of a way to change the container linking during runtime. This image assumes you have to simply create a new container with your updated linking in place.

Several other images exist that either use a dedicated database that exposes these kind of settings during runtime or otherwise directly communicate with the docker daemon to query running containers. These are valid options for more dynamic setups, however IMO these kind of things are out of scope for _this_ image.

That being said, I'm not opposed to looking into our available options. If docker ever were to support changing container linking during runtime, I'd love to see this being supported in this image! :+1: 

> If anyone is interested in this, please let me know.

I am :-)
